name: markdown-check

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
        continue-on-error: true

      - name: link check (relative links)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/mlc_config.json"
        continue-on-error: true
